data_dir: ../../../datasets/contrastive/processed
dataset_name: clinc150
st_model_name: all-mpnet-base-v2
batch_size: 4
train_data_file_name: train_contrastive_clinc150_neg_samp2.csv
dev_data_dir: ../../../datasets/contrastive/banking77/
dev_data_file_name: train_contrastive_banking77_neg_samp2.csv
debug: False
train_loss: contrastive_loss
cp_dir: checkpoint
evaluation_steps: 20
steps_per_epoch: 10000
save_best_model: True
epochs: 5
warmup_steps: 100



# st_model_name: all-MiniLM-L12-v2
# st_model_name: quora-distilbert-multilingual
# st_model_name: paraphrase-multilingual-mpnet-base-v2
# st_model_name: all-distilroberta-v1
# st_model_name: multi-qa-distilbert-cos-v1