data_dir: ../../../../../datasets/processed/baseline-ft-contrastive/
dataset_name: hwu64
st_model_name: all-mpnet-base-v2
batch_size: 4
# train_data_file_name: train_hwu64.csv
train_data_file_name: all_hwu64_contrastive_data_neg_samples_20.csv
dev_data_dir: ../../../../../datasets/processed/clinc150/
dev_data_file_name: contrastive_val_GZS_neg_samples_3.csv
debug: False
train_loss: contrastive_loss
cp_dir: checkpoint_1
evaluation_steps: 20
epochs: 10
warmup_steps: 100



# st_model_name: all-MiniLM-L12-v2
# st_model_name: quora-distilbert-multilingual
# st_model_name: paraphrase-multilingual-mpnet-base-v2
# st_model_name: all-distilroberta-v1
# st_model_name: multi-qa-distilbert-cos-v1